apiVersion: apps/v1
kind: Deployment
metadata:
  name: minecraft-server
  labels:
    role: server
spec:
  replicas: 1
  selector:
    matchLabels:
      role: server
  template:
    metadata:
      labels:
        role: server
    spec:
      containers:
      - name: server
        image: eu.gcr.io/kyiro-gcp-games/minecraft:latest
        ports:
        - containerPort: 25565
          protocol: TCP
        resources:
          requests:
            cpu: 1.25
            memory: 6Gi
          limits:
            memory: 6Gi
        volumeMounts:
        - name: config
          mountPath: /opt/minecraft/server.properties
          subPath: server.properties
          readOnly: true
        - name: config
          mountPath: /opt/minecraft/whitelist.json
          subPath: whitelist.json
          readOnly: true
        - name: world
          mountPath: /opt/minecraft/world
      volumes:
      - name: config
        configMap:
          name: server-config
      - name: world
        persistentVolumeClaim:
          claimName: minecraft-world
