apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: minecraft

commonLabels:
  app: minecraft

resources:
- statefulset.yaml
- service.yaml

configMapGenerator:
- name: server-config
  files:
  - server.properties
  - whitelist.json
