apiVersion: v1
kind: Service
metadata:
  name: minecraft
  annotations:
   external-dns.alpha.kubernetes.io/hostname: minecraft.gcp.kyiro.net
spec:
  selector:
    role: server
  type: NodePort
  ports:
  - port: 25565
    targetPort: 25565
    nodePort: 30000
    protocol: TCP
