apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: quake3

commonLabels:
  app: quake3

resources:
- deployment.yaml
- service.yaml

configMapGenerator:
- name: server-config
  files:
  - server.cfg
