apiVersion: v1
kind: Service
metadata:
  name: quake3
  annotations:
   external-dns.alpha.kubernetes.io/hostname: q3.gcp.kyiro.net
   external-dns.alpha.kubernetes.io/ttl: "60"
spec:
  selector:
    role: server
  type: NodePort
  ports:
  - port: 27960
    targetPort: 27960
    nodePort: 30100
    protocol: UDP
